CREATE TABLE USERS if NOT EXISTS(
    id NUMBER PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    cnpj VARCHAR2(14) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL
);


CREATE TABLE DADOS if NOT EXISTS(
    id NUMBER PRIMARY KEY,
    faturamento VARCHAR2(100) NOT NULL,
    fluxo_vendas VARCHAR2(100) NOT NULL,
    clientes VARCHAR2(100) NOT NULL,
    acessos_plataforma VARCHAR2(100) NOT NULL,
    users_id NUMBER,
    CONSTRAINT fk_users_dados FOREIGN KEY (users_id) REFERENCES USERS(id)
);
